name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ '8.1', '8.2' ]
        laravel: [ '^10.0' ]
        dependency-version: [ prefer-stable ]
        include:
          - laravel: '^10.0'
            testbench: '^8.0'

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, xml, ctype, iconv, json, pdo_sqlite, tokenizer
          coverage: xdebug

      - name: Install Dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-update
          composer require --dev "orchestra/testbench:${{ matrix.testbench }}" --no-update
          composer update --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
